name: gopher-greeter-CICD

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

defaults:
  run:
    working-directory: .

jobs:
  # The “build” workflow
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up GO 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Build using Taskfile
        run: task build
