name: gopher-greeter-CICD

on:
  push:
    branches:
      - master
      - develop

defaults:
  run:
    working-directory: .

jobs:
  # The “build” workflow
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up GO 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Build using Taskfile
        run: task build

      - name: Trigger Git-Tag workflow
        #if: ${{ (github.event_name != 'workflow_dispatch' && success()) || (github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_next && success()) }}
        if:  ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && success() }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: git-tag-workflow
