name: gopher-greeter-release

on:
  push:
    tags:
      - '*'
    branches:
      - master


jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: '0'

#      - name: Bump version and push tag
#        uses: anothrNick/github-tag-action@1.36.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          REPO_OWNER: abhinav812
#          WITH_V: true
#          VERBOSE: true

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO_OWNER: abhinav812