name: Bump version

on:
  repository_dispatch:
    types: [git-tag-workflow]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: abhinav812
          WITH_V: true
          VERBOSE: true

      - name: Trigger Release workflow
        if:  ${{ github.ref == 'refs/heads/master' && success() }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: git-release-workflow